---

# https://github.com/Homebrew/homebrew-completions

bash_completion_formulae:
  - brew-cask-completion
  # TODO: Fails build.
  # No available formula with the name "homebrew/completions/composer-completion"
  # - composer-completion
  - docker-completion
  - docker-compose-completion
  - docker-machine-completion
  - vagrant-completion
