---

- name: Ensure excluded directory exists
  file:
    path: /Users/{{ ansible_env.USER }}/{{ time_machine_ex_dir_name }}
    state: directory

# TODO: Not sure if you can do -array-add via the osx_defaults module
- name: Show Time Machine in menu bar
  command: defaults write com.apple.systemuiserver menuExtras -array-add "/System/Library/CoreServices/Menu Extras/TimeMachine.menu"
  notify: killall SystemUIServer
