---

# https://docs.travis-ci.com/user/osx-ci-environment

matrix:
  include:
    # macOS 10.12
    - os: osx
      osx_image: xcode8.2
    # macOS 10.11
    - os: osx
      osx_image: xcode8

install:
  # Debug info
  - python --version
  # Run setup script
  - bash init.sh
  # Debug info
  - pip --version
  - ansible --version

script:
  # Playbook syntax check
  - ansible-playbook mac.yml --syntax-check
  # Role specific test
  # - ansible-playbook mac.yml -t "evernote"
  # Run Ansible playbook:
  # - Skip tasks/roles that we know cause issues in Travis
  # - Skip stage 3/4 roles as they don't *really* add much to the test
  - ansible-playbook mac.yml --skip-tags "no_ci,stage_3,stage_4"
